from django.db import models

# Create your models here.
class Player(models.Model):
    coins = models.IntegerField()
    name = models.CharField(max_length=300)
    avatar = models.CharField(max_length=1000)

class Steam(models.Model):
    steamId = models.CharField(max_length=300)
    player = models.ForeignKey(Player)

class Item(models.Model):
    player = models.ForeignKey(Player)
    flag = models.IntegerField()
    idBase = models.IntegerField()    

class Mercenary(models.Model):
    player = models.ForeignKey(Player)
    idBase = models.IntegerField()
    nombre = models.CharField(max_length=300)
    nivel = models.IntegerField()
    exp = models.IntegerField()
    agilidad = models.IntegerField()
    destreza = models.IntegerField()
    constitucion = models.IntegerField()
    fuerza = models.IntegerField()
    inteligencia = models.IntegerField()
    sabiduria = models.IntegerField()
    carisma = models.IntegerField()
    poder = models.IntegerField()
    marcial = models.IntegerField()
    stealth = models.IntegerField()
    magia = models.IntegerField()
    tecnologia = models.IntegerField()
    crecimientoAgilidad = models.IntegerField()
    crecimientoDestreza = models.IntegerField()
    crecimientoConstitucion = models.IntegerField()
    crecimientoFuerza = models.IntegerField()
    crecimientoInteligencia = models.IntegerField()
    crecimientoSabiduria = models.IntegerField()
    crecimientoCarisma = models.IntegerField()
    crecimientoPoder = models.IntegerField()
    crecimientoMarcial = models.IntegerField()
    crecimientoStealth = models.IntegerField()
    crecimientoMagia = models.IntegerField()
    crecimientoTecnologia = models.IntegerField()
    hpCalculo = models.CharField(max_length=300)
    item1 = models.ForeignKey(Item, related_name='item1_id', null=True)
    item2 = models.ForeignKey(Item, related_name='item2_id', null=True)
    item3 = models.ForeignKey(Item, related_name='item3_id', null=True)
    item4 = models.ForeignKey(Item, related_name='item4_id', null=True)
    item5 = models.ForeignKey(Item, related_name='item5_id', null=True)
    item6 = models.ForeignKey(Item, related_name='item6_id', null=True)
    hpMax = models.IntegerField()
    hpActual = models.IntegerField()
    misionActual = models.IntegerField()
